---
title: "R_GillRakerStatisticalAnalyses"
author: "Chelsea Bishop"
date: "January 3, 2020"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE, fig.width=12, fig.height=8)
```

Gill Rakers
```{r Gill Raker Data}
setwd("~/")
rakerData<- read.csv("Gill_Rakers_2018_Final.csv")
fishID<-rakerData$fishID
captureMethod<-rakerData$capture_Method
lakeID<-rakerData$lakeID
DOClevel<-rakerData$DOCbin
DOC<-rakerData$lakeDOC
fishLength<-rakerData$fishSL
rakercount<-rakerData$total_RakerNum
avgRakerLength<-rakerData$avgRakerLength
avgRakerSpace<-rakerData$avgRakerSpace
length.avg.ss<-rakerData$SS.Length
space.avg.ss<-rakerData$SS.Space
count.ss<-rakerData$SS.Count


length1<-rakerData$length_Raker1
length2<-rakerData$length_Raker2
length3<-rakerData$length_Raker3
length4<-rakerData$length_Raker4
length5<-rakerData$length_Raker5
length6<-rakerData$length_Raker6
length7<-rakerData$length_Raker7
length8<-rakerData$length_Raker8
length9<-rakerData$length_Raker9
space1<-rakerData$space1
space2<-rakerData$space2
space3<-rakerData$space3
space4<-rakerData$space4
space5<-rakerData$space5
space6<-rakerData$space6
space7<-rakerData$space7
space8<-rakerData$space8

dfraker<-data.frame(captureMethod<-rakerData$capture_Method,lakeLss=rakerData$avgrakerlengthSS_bylake,lakeSss=rakerData$avgrakerspaceSS_bylake,lakeCss=rakerData$rakercountSS_bylake,rakercount=rakerData$total_RakerNum,DOClevel=rakerData$DOCbin,DOC=rakerData$lakeDOC,Lake=rakerData$lakeID,fishLength=rakerData$fishSL,avgRakerLength=rakerData$avgRakerLength,avgRakerSpace=rakerData$avgRakerSpace,count.ss=rakerData$SS.Count, length.ss=rakerData$SS.Length,space.ss=rakerData$SS.Space,avgL2<-rakerData$avgL_4.7,avgS2<-rakerData$avgS_4.6)

```

```{r Gill Raker Size Standardization}
size.rem.L<-lm(log10(avgRakerLength) ~ log10(fishLength)*lakeID, data=dfraker)
size.rem.S<-lm(log10(avgRakerSpace) ~ log10(fishLength)*lakeID, data=dfraker)
size.rem.C<-lm(log10(rakercount) ~ log10(fishLength)*lakeID, data=dfraker)
summary(size.rem.L)
## NOTE!Interaction effect for FD,LC,SQ,TO
summary(size.rem.S)
## NOTE!Interaction effect for FD,LC,SQ,TO
summary(size.rem.C)
## NOTE!Interaction effect for FD,SQ

## Remove lake ID so can get the intercept for size
size.rem2L<-lm(log10(avgRakerLength) ~ log10(fishLength)+lakeID, data=dfraker)
summary(size.rem2L)
size.rem2S<-lm(log10(avgRakerSpace) ~ log10(fishLength)+lakeID, data=dfraker)
summary(size.rem2S)
size.rem2C<-lmsize.rem.C<-lm(log10(rakercount) ~ log10(fishLength)+lakeID, data=dfraker)
summary(size.rem2C)

## COMPARE MODELS USING GENERAL LINEAR TEST, change order so that get positive differences in Df and SS
anova(size.rem2L,size.rem.L)
anova(size.rem2S,size.rem.S)
anova(size.rem2C,size.rem.C)
## All highly significant, therefore more complex model is better to explain data. This means that including an interaction between lake and fish length provides a more parsimonious way of estimating raker characteristics. Gillraker length etc, changes with body size and this varies by lake! Affected by DOC??


Lakespec.ss<-lm(log10(lakeLss) ~ log10(fishLength)*lakeID, data=dfraker)
size.rem2L.lake<-lm(log10(lakeLss) ~ log10(fishLength)+lakeID, data=dfraker)
###Compared lake-specific size standardizations, ineraction model here NOT better.
anova(size.rem2L.lake,Lakespec.ss)

###Compare lake specific and non
lakespecificAIC<-AIC(size.rem2L.lake,size.rem2L)*-2
View(lakespecificAIC)
###lower AIC for non lake-specific slope model


Lakespec.ssL<-lm(log10(lakeLss) ~ log10(fishLength)*lakeID, data=dfraker)
Lakespec.ssS<-lm(log10(lakeSss) ~ log10(fishLength)*lakeID, data=dfraker)
Lakespec.ssC<-lm(log10(lakeCss) ~ log10(fishLength)*lakeID, data=dfraker)
## Plot fitted values from model against DOC to see if DOC is driver of allometric relationships varying by lake
library(VGAM)
p1<-data.frame(DOC=dfraker$DOC, fittedRakerLength=fitted(Lakespec.ssL))
p2<-data.frame(DOC=dfraker$DOC, fittedRakerSpace=fitted(Lakespec.ssS))
p3<-data.frame(DOC=dfraker$DOC, fittedRakerCount=fitted(Lakespec.ssC))
library(ggplot2)
ggplot(p1, aes(DOC, fittedRakerLength)) + geom_smooth() + geom_point(size=4, shape=1, alpha=0.6)
ggplot(p2, aes(DOC, fittedRakerSpace)) + geom_smooth() + geom_point(size=4, shape=1, alpha=0.6)
ggplot(p3, aes(DOC, fittedRakerCount)) + geom_smooth() + geom_point(size=4, shape=1, alpha=0.6)

#......

AIC.gill.length<-AIC(size.rem2L,size.rem.L)
AIC.gill.space<-AIC(size.rem2S,size.rem.S)
AIC.gill.count<-AIC(size.rem2C,size.rem.C)
LengthAIC=-2*AIC.gill.length ### Multiply log-likelyhood by -2 to make AIC's positive, apparently it is -2 and not -1 for historical reasons??? 
SpaceAIC=-2*AIC.gill.space
CountAIC=-2*AIC.gill.count
View(LengthAIC)
### size.rem2 slightly lower AIC, so slightly more parsimonious model is one without interaction
View(SpaceAIC)
View(CountAIC)
### size.rem2 slightly lower AIC, so slightly more parsimonious model is one without interaction

### this differs from conclusion made from F-test, why???

library(lmerTest)
library(lme4)
## Run model with size standardized values 
MeristicRakerLength<-lmer(log10(length.ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerLength)
MeristicRakerSpace<-lmer(log10(space.ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerSpace)
MeristicRakerCount<-lmer(log10(count.ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerCount)

### lake specific size standardization
rakerLength_lakess<-lmer(log10(lakeLss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(rakerLength_lakess)
rakerSpace_lakess<-lmer(log10(lakeSss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(rakerSpace_lakess)
rakerCount_lakess<-lmer(log10(lakeCss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(rakerCount_lakess)

###DOC significant in all, this differs from common slope as there is no significant effect of DOC on count in common slope model.

AIC(MeristicRakerLength,rakerLength_lakess)*-2
##AIC of lakespecific slope vs common on new models still is lower with common slope, which suggests it is more parsimonious


###What about with gear???

```
```{r Gill Raker Plots}
library(ggplot2)
midRL<-mean(rakerData$DOC) ### problems with this, getting NA so just set midpoint to 10


ggplot(dfraker,aes(x = lakeID , y = captureMethod)) + 
  geom_point(aes(colour = DOC)) + 
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(dfraker,aes(x = captureMethod , y = length.ss)) + 
  geom_point(aes(colour = DOC)) + 
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")


midRL<-mean(dfraker$DOC)
ggplot(dfraker,aes(x = captureMethod, y = log10(length.ss), colour = DOC)) + 
  geom_point()+
  scale_y_log10()+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")


ggplot(dfraker,aes(x = log10(fishLength), y = log10(space.ss))) + 
  geom_point(aes(colour = DOC)) + 
  scale_y_log10()+
  scale_colour_gradient2(midpoint=midRL, low="cadetblue1", mid="deepskyblue",high="chocolate4")
ggplot(dfraker,aes(x = captureMethod, y = log10(space.ss))) + 
  geom_point(aes(colour = DOC)) + 
  scale_y_log10()+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")


ggplot(dfraker,aes(x = log10(fishLength), y = log10(count.ss))) + 
  geom_point(aes(colour = DOC)) + 
  scale_y_log10()+
  scale_colour_gradient2(midpoint=midRL, low="cadetblue1", mid="deepskyblue",high="chocolate4")
ggplot(dfraker,aes(x = captureMethod, y = count.ss)) + 
  geom_point(aes(colour = DOC)) + 
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(dfraker,aes(x = log10(DOC), y = log10(length.ss))) + 
  geom_point(aes(colour = DOC)) +
  scale_y_log10()+
  scale_colour_gradient2(midpoint=midRL, low="cadetblue1", mid="deepskyblue",high="chocolate4")


ggplot(dfraker,aes(x = log10(DOC), y = log10(space.ss))) + 
  geom_point(aes(colour = DOC)) + 
  scale_y_log10()+
  scale_colour_gradient2(midpoint=midRL, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(dfraker,aes(x = DOC, y = count.ss)) + 
  geom_point(aes(colour = DOC)) + 
  scale_y_log10()+
  scale_colour_gradient2(midpoint=midRL, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(dfraker,aes(x =DOC, y = count.ss))+
  geom_point(aes(colour = lakeID))+
  scale_y_log10()+
  scale_color_manual(values = c("#00BFFF","#47B5EB", "#5FACD8", "#6FA2C5", "#7B99B3", "#838FA0", "#88868E", "#8C7D7C", "#8F736B", "#906A5A", "#906148", "#8F5837","#8D4E26", "#8B4513"), 
                     name="Lake",
                    breaks=c("Lost","Little_Crooked","Crampton","Towanda","Found","Papoose","Muskellunge","Bay","Birch","Oxbow","McCullough","Red Bass","Squaw","Hummingbird"))


cc <- scales::seq_gradient_pal("deepskyblue", "chocolate4", "Lab")(seq(0,1,length.out=14))


MLSS<-lmer(log10(length.ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MLSS)  
ML3<-lmer(log(avgRakerLength) ~ 1 + log(fishLength)+log(DOC) + (1+log(fishLength)|Lake), data=dfraker)
summary(ML3)
ML3.2<-lmer(log(avgRakerLength) ~ 1 + log(fishLength)*log(DOC) + (1+log(fishLength)|Lake), data=dfraker)
summary(ML3.2)

coef(ML3)
fixef(ML3)
ranef(ML3)

ggplot(dfraker,aes(x = log10(DOC), y = log10(avgL2_ss))) + 
  geom_point(aes(colour = DOC)) +
  scale_y_log10()+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(dfraker,aes(x = log10(DOC), y = log10(avgS2_2ss))) + 
  geom_point(aes(colour = DOC)) +
  scale_y_log10()+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(dfraker,aes(x = log10(DOC), y = log10(count.ss))) + 
  geom_point(aes(colour = DOC)) +
  scale_y_log10()+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")
```
```{r Gill Raker Variance}
### Calculate variance between lakes
## raker length
library(dplyr)
library(ggplot2)
lengthVar<-dfraker %>% group_by(Lake) %>% summarise(var=var(length.ss))
spaceVar<-dfraker %>% group_by(Lake) %>% summarise(var=var(space.ss))
countVar<-dfraker %>% group_by(Lake) %>% summarise(var=var(count.ss)) 
setwd("~/MCGILL/Bluegill Sunfish Data/2018 Photos/GILL RAKERS")
var.dat<-read.csv("raker_variances.csv")
DOCvar<-var.dat$DOC
DOCbin<-var.dat$DOC_bin
lakevar<-var.dat$Lake
lengthvar<-var.dat$rakerL_var
spacevar<-var.dat$rakerS_var
countvar<-var.dat$rakerC_var
capturevar<-var.dat$captureMethod
df.var<-data.frame(DOCvar<-var.dat$DOC,DOCbin<-var.dat$DOC_bin,
                   lakevar<-var.dat$Lake,
                   lengthvar<-var.dat$rakerL_var,
                   spacevar<-var.dat$rakerS_var,
                   countvar<-var.dat$rakerC_var,capturevar<-var.dat$captureMethod)

ggplot(df.var,aes(x = lakevar, y = lengthvar)) + 
  geom_point(aes(colour = DOCvar)) +
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")
ggplot(df.var,aes(x = capturevar, y = lengthvar)) + 
  geom_point(aes(colour = DOCvar)) +
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(df.var,aes(x = lakevar, y = spacevar)) + 
  geom_point(aes(colour = DOCvar)) +
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")
ggplot(df.var,aes(x = capturevar, y = spacevar)) + 
  geom_point(aes(colour = DOCvar)) +
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(df.var,aes(x = lakevar, y = countvar)) + 
  geom_point(aes(colour = DOCvar)) +
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")
ggplot(df.var,aes(x = capturevar, y = countvar)) + 
  geom_point(aes(colour = DOCvar)) +
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")
mean.var_per_bin<-aggregate(df.var[, 4:6], list(df.var$DOCbin), mean)
###variance in high DOC bin much higher in raker length compared to other bins, but this is likely being driven by SQ. Also the case with spaces.
### high DOC lakes have lowest variance in count.
### Group.1 lengthvar....var.dat.rakerL_var spacevar....var.dat.rakerS_var countvar....var.dat.rakerC_var
#1     0-10                        4.705000                       1.374125                       1.369625
#2 10-15.00                        4.573333                       0.448000                       1.790000
#3    15-25                        8.890000                       1.950667                       0.980000
```

```{r Final Stats}
rakerData<- read.csv("Gill_Rakers_2018_Final.csv")
dfraker<-data.frame(captureMethod<-rakerData$capture_Method,lakeLss=rakerData$avgrakerlengthSS_bylake,lakeSss=rakerData$avgrakerspaceSS_bylake,lakeCss=rakerData$rakercountSS_bylake,rakercount=rakerData$total_RakerNum,DOClevel=rakerData$DOCbin,DOC=rakerData$lakeDOC,Lake=rakerData$lakeID,fishLength=rakerData$fishSL,avgRakerLength=rakerData$avgRakerLength,avgRakerSpace=rakerData$avgRakerSpace,count.ss=rakerData$SS.Count, length.ss=rakerData$SS.Length,space.ss=rakerData$SS.Space,avgL2<-rakerData$avgL_4.7,avgS2<-rakerData$avgS_4.6,avgL2_ss<-rakerData$avgL2_ss,avgS2_2ss<-rakerData$avgS2_ss, basin.raker<-rakerData$basin)
###Change raker averages to just those of rakers4-7 and spaces 4-6

size.rem.L2<-lm(log10(avgL2) ~ log10(fishLength)*Lake, data=dfraker)
size.rem.S2<-lm(log10(avgS2) ~ log10(fishLength)*Lake, data=dfraker)

summary(size.rem.L2)
## NOTE!Interaction effect for FD,LC,Lt,RB,SQ,TO
summary(size.rem.S2)
## NOTE!Interaction effect for FD,LC,SQ,TO
## Remove lake ID so can get the intercept for size
size.rem2L<-lm(log10(avgL2) ~ log10(fishLength)+Lake, data=dfraker)
summary(size.rem2L)
size.rem2S<-lm(log10(avgS2) ~ log10(fishLength)+Lake, data=dfraker)
summary(size.rem2S)



###Run size-standardized models with new raker selection
MeristicRakerLength<-lmer(log10(avgL2_ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerLength)
MeristicRakerSpace<-lmer(log10(avgS2_2ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerSpace)
### NOTE: Still a positive correlation of length and space with DOC
MeristicRakerCount<-lmer(log10(rakercount) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerCount)
##get intercepts, ranef gets pts centered around a mean of zero
ranef(MeristicRakerLength)
ranef(MeristicRakerSpace)
ranef(MeristicRakerCount)
##coef takes each point and adds it to the overall mean so that you get actual predicted lake value
coef(MeristicRakerLength)
coef(MeristicRakerSpace)
coef(MeristicRakerCount)
##get S.E.'s
se.ranef(MeristicRakerLength)
se.ranef(MeristicRakerSpace)
se.ranef(MeristicRakerCount)

se.coef(MeristicRakerLength)
se.coef(MeristicRakerSpace)
se.coef(MeristicRakerCount)
##create dataframe to make figure
rakerS.E<-read.csv("rakerdata_2020_copy2.csv")
df.raker.SE<-data.frame(DOC.SE<-rakerS.E$DOC,lakeID.R<-rakerS.E$Lake,Ls.e<-rakerS.E$SE_L,Ss.e<-rakerS.E$SE_S,Cs.e<-rakerS.E$SE_C,Lrs.e<-rakerS.E$rSE_L,Srs.e<-rakerS.E$rSE_S,Crs.e<-rakerS.E$rSE_C,L<-rakerS.E$coef_L,S<-rakerS.E$coef_S,C<-rakerS.E$coef_C,Lr<-rakerS.E$ranef_L,Sr<-rakerS.E$ranef_S,Cr<-rakerS.E$ranef_C, fittedRL<-rakerS.E$fitted_L,fittedRS<-rakerS.E$fitted_S,fittedRN<-rakerS.E$fitted_C, basin.raker.SE<-rakerS.E$basin, maxdepth<-rakerS.E$max_Depth.m., area<-rakerS.E$surface_Area.ha., trout<-rakerS.E$Trout,LMB<-rakerS.E$LMB,SMB<-rakerS.E$SMB,Musk<-rakerS.E$Musk,Pike<-rakerS.E$Pike,Wall<-rakerS.E$Walleye)

ggplot(rakerS.E,aes(x = DOC.SE, y )) + 
  geom_point(aes(colour = DOC.SE)) + 
  geom_errorbar(aes(ymin=L-Ls.e), ymax=(L+Ls.e))+
  scale_colour_gradient2(midpoint=mid, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(rakerS.E,aes(x = DOC.SE, y =S)) + 
  geom_point(aes(colour = DOC.SE)) + 
  geom_errorbar(aes(ymin=S-Ss.e), ymax=(S+Ss.e))+
  scale_colour_gradient2(midpoint=mid, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(rakerS.E,aes(x = DOC.SE, y =C)) + 
  geom_point(aes(colour = DOC.SE)) + 
  geom_errorbar(aes(ymin=C-Cs.e), ymax=(C+Cs.e))+
  scale_colour_gradient2(midpoint=mid, low="cadetblue1", mid="deepskyblue",high="chocolate4")

##Look into count and size relationship
ggplot(dfraker,aes(x = rakercount, y =fishLength)) + 
  geom_point(aes(colour = DOC)) + 
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

MeristicRakerCount.Length<-lmer(log10(rakercount) ~ 1 + log10(fishLength) + (1|Lake), data=dfraker)
summary(MeristicRakerCount.Length)
##Significant negative relationship woo! The smaller fish have less gill rakers

```

```{r}
###Adjustments

fitted(MeristicRakerLength)
fitted(MeristicRakerSpace)
fitted(MeristicRakerCount)

anova(MeristicRakerLength)
anova(MeristicRakerSpace)
anova(MeristicRakerCount)

ggplot(rakerS.E,aes(x = DOC.SE, y =fittedRL, label=lakeID.R)) + 
  geom_point(aes(colour = DOC.SE)) + 
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.R),hjust=0, vjust=0)+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(rakerS.E,aes(x = DOC.SE, y =fittedRS, label=lakeID.R)) + 
  geom_point(aes(colour = DOC.SE)) + 
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.R),hjust=0, vjust=0)+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(rakerS.E,aes(x = DOC.SE, y =fittedRN, label=lakeID.R)) + 
  geom_point(aes(colour = DOC.SE)) + 
 geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.R),hjust=0, vjust=0)+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

ggplot(rakerS.E,aes(x = fittedRS, y =fittedRL, label=lakeID.R)) + 
  geom_point(aes(colour = DOC.SE)) + 
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.R),hjust=0, vjust=0)+
  scale_colour_gradient2(midpoint=10, low="cadetblue1", mid="deepskyblue",high="chocolate4")

#Need GLM for count data??
plot(MeristicRakerCount)
###Not normally distributed

countGLM<-glmer(log10(rakercount) ~ 1 + log10(DOC) + (1|Lake),family = poisson,nAGQ=0,control=glmerControl(optimizer = "nloptwrap"), data=dfraker)
plot(countGLM)
qqnorm(residuals(countGLM))
anova(countGLM)
summary(countGLM)

#compare to original model
qqnorm(residuals(MeristicRakerCount))
ggplot(data.frame(eta=predict(MeristicRakerCount,type="link"),pearson=residuals(MeristicRakerCount,type="pearson")),
      aes(x=eta,y=pearson)) +
    geom_point() +
    theme_bw()
###Similar results, not perfect but nothing to be concerned about. Still going to go with glmer with poisson because it is better for count data. 

###Basin
MeristicRakerLength_basin<-lmer(log10(avgL2_ss) ~ 1 + log10(DOC)*basin.raker + (1|Lake), data=dfraker)
summary(MeristicRakerLength_basin)
MeristicRakerSpace_basin<-lmer(log10(avgS2_2ss) ~ 1 + log10(DOC)*basin.raker + (1|Lake), data=dfraker)
summary(MeristicRakerSpace_basin)


###Compare models
M1.g<-lmer(log10(count.ss) ~ 1 + log10(DOC)*basin.raker + (1|Lake), data=dfraker)
M2.g<-lmer(log10(count.ss) ~ 1 + log10(DOC)+basin.raker + (1|Lake), data=dfraker)
M3.g<-lmer(log10(count.ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
M4.g<-lmer(log10(count.ss) ~ 1 + log10(DOC)+(1|basin.raker) + (1|Lake), data=dfraker)
M5.g<-lmer(log10(count.ss) ~ 1 + log10(DOC)+ (1+Lake|basin.raker), data=dfraker)
M6.g<-lmer(log10(count.ss) ~ 1 + log10(DOC)+ (1+basin.raker|Lake), data=dfraker)
M7.g<-lmer(log10(count.ss) ~ 1 + log10(DOC)+ (1|Lake)+(1|basin.raker) , data=dfraker)
# ii) Compare models using AICc values
library(AICcmodavg)
# Compute AICc values for each model
AICc.g<-c( AICc(M1.g), AICc(M2.g), AICc(M3.g), AICc(M4.g), AICc(M5.g),AICc(M6.g),AICc(M7.g))
# Put values into one table for easy comparision
Model.g<-c("M1.g", "M2.g", "M3.g", "M4.g", "M5.g","M6.g","M7.g")
AICtable.g<-data.frame(Model=Model.g, AICc=AICc.g)
AICtable.g

###Lowest AIC includes basin for raker length, all others prefer just DOC, and lake as a random factor


ggplot(rakerS.E,aes(x = DOC.SE, y =fittedRL, label= lakeID.SE, colour=basin.raker.SE)) + 
  geom_point(aes(colour = basin.raker.SE)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

ggplot(rakerS.E,aes(x = DOC.SE, y =fittedRS, label= lakeID.SE, colour=basin.raker.SE)) + 
  geom_point(aes(colour = basin.raker.SE)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

ggplot(rakerS.E,aes(x = DOC.SE, y =fittedRN, label= lakeID.SE, colour=basin.raker.SE)) + 
  geom_point(aes(colour = basin.raker.SE)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)


###Other Comparisons with Lake Characteristics vs Raker Length


ggplot(rakerS.E,aes(x = DOC.SE, y = fittedRL, label= lakeID.SE, colour=maxdepth)) + 
  geom_point(aes(colour = maxdepth)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

ggplot(rakerS.E,aes(x = DOC.SE, y = fittedRL, label= lakeID.SE, colour=area)) + 
  geom_point(aes(colour = area)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

ggplot(rakerS.E,aes(x = DOC.SE, y = fittedRS, label= lakeID.SE, colour=maxdepth)) + 
  geom_point(aes(colour = maxdepth)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

ggplot(rakerS.E,aes(x = DOC.SE, y = fittedRS, label= lakeID.SE, colour=area)) + 
  geom_point(aes(colour = area)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

ggplot(rakerS.E,aes(x = DOC.SE, y = fittedRN, label= lakeID.SE, colour=maxdepth)) + 
  geom_point(aes(colour = maxdepth)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

ggplot(rakerS.E,aes(x = DOC.SE, y = fittedRN, label= lakeID.SE, colour=area)) + 
  geom_point(aes(colour = area)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)

##Examining raker length vs space
ggplot(rakerS.E,aes(x = fittedRL, y = fittedRS, label= lakeID.SE, colour=DOC.SE)) + 
  geom_point(aes(colour = DOC.SE)) +
  geom_smooth(method = 'lm')+
  geom_text(aes(label=lakeID.SE),hjust=0, vjust=0)
##Examining "best" model for raker length as it differs from others. Note no difference in overall message
M6.g<-lmer(log10(length.avg.ss) ~ 1 + log10(DOC)+ (1+basin.raker|Lake), data=dfraker)
summary(M6.g)

min(avgL2_ss)
##11.62
max(avgL2_ss)
##33.08
min(avgS2_2ss)
##2.51
max(avgS2_2ss)
##17.97
min(rakercount)
#9
max(rakercount)
#15
```

```{r}
#FINAL MODELS

#Length
MeristicRakerLength<-lmer(log10(avgL2_ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerLength)
#Space
MeristicRakerSpace<-lmer(log10(avgS2_2ss) ~ 1 + log10(DOC) + (1|Lake), data=dfraker)
summary(MeristicRakerSpace)
#Number
countGLM<-glmer(log10(rakercount) ~ 1 + log10(DOC) + (1|basin.raker/Lake),family = poisson,nAGQ=0,control=glmerControl(optimizer = "nloptwrap"), data=dfraker)
anova(countGLM)
summary(countGLM)
```


